server:
  port: 9000

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.135.230:33110/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
  session:
    store-type: redis
    redis:
      flush-mode: on_save # 保存时才刷新
      namespace: spring:session # session存在redis中的key
  rabbitmq:
    host: 49.235.135.230
    port: 5672
    virtual-host: /avengereug
    username: guest
    password: guestguest
    listener:
      direct:
        retry:
          enabled: false
#      simple:
#        # 设置手动ack确认模式
#        acknowledge-mode: manual
    # 开启交换机路由至队列失败的回调
    publisher-returns: true
    # 代替publisher-confirms配置，阅读源码后能发现此配置的底层就是来配置publisher-confirm-type的
    # 因此publisher-confirm-type配置也是开启可靠消息投递的模式的
    publisher-confirm-type: correlated

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      # 设置mybatis-plus 主键自增(等数据量大后，需要分库分表，此时此种方案肯定不可取，目前先这么干)
      id-type: auto