server:
  port: 20000

spring:
  application:
    name: service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        min-idle: 10
        max-idle: 50