server:
  port: 20000
  servlet:
    session:
      timeout: 30m #session超时时间

spring:
  application:
    name: service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
  session:
    store-type: redis
    redis:
      flush-mode: on_save # 保存时才刷新
      namespace: spring:session # session存在redis中的key